Tickets/dm 26702
lsst-ts/ts_salobj pull request #155
Opened 2020-10-09 21:13 UTC by colinwinslow

2020-10-09 21:30 UTC, rbovill approved these changes
Jenkinsfile.conda updates look good.

2020-10-12 18:04 UTC, rbovill requested changes
Please squash and rebase.

2020-10-17 00:01 UTC, rbovill approved these changes

2020-10-27 16:17 UTC, tribeiro approved these changes

2020-10-27 16:53 UTC, merged