DM-27296: update to get DDS QoS settings from ts_ddsconfig instead of ts_idl
lsst-ts/ts_salobj pull request #159
Opened 2020-10-26 22:17 UTC by r-owen

2020-10-27 02:09 UTC, tribeiro requested changes
Please, don't merge this PR until I have a chance to add the package to the develop-env container or it will break everything!

2020-10-30 23:32 UTC, couger01 approved these changes
LGTM.

2020-11-16 19:03 UTC, tribeiro commented on conda/meta.yaml
>      - boto3
can you update the test requirements to use the new `ts-conda-build` meta package? should be something like:

```
    - ts-conda-build
    - ts-ddsconfig
    - ts-dds
    - ts-idl
```

2020-11-16 19:04 UTC, tribeiro approved these changes

2020-11-16 20:03 UTC, merged