Add conda install instructions
lsst-ts/ts_salobj pull request #166
Opened 2020-11-30 13:36 UTC by couger01

2020-12-04 22:42 UTC, tribeiro commented
@couger01, you need to rebase this branch.

2020-12-04 22:45 UTC, tribeiro commented on doc/index.rst
> +ts_salobj is offered as a conda package.
Note that we also offer salobj in pypi, so you can actually do `pip install ts-salobj` as well.

2020-12-04 22:46 UTC, tribeiro requested changes
This is a good start but I think it would be good to expand this with all the information needed to install salobj on centos. From installing OpenSplice with yum, all the way to having salobj up and running, both with conda and pypi.

2020-12-10 12:23 UTC, pkubanek approved these changes

2020-12-10 12:25 UTC, pkubanek approved these changes
I wrote something on similar tone for installing, but never merged it. Thanks for providing this missing piece.

2020-12-31 17:37 UTC, closed without merging