DM-33535: Implement new configuration system
lsst-ts/ts_salobj pull request #223
Opened 2022-02-05 02:05 UTC by r-owen

2022-02-10 20:53 UTC, wvreeven requested changes
If I understand correctly, `valid_simulation_modes` cannot be None anymore but there still are cases where this can be the case, as indicated by my comments. Please also fix the build by making changes to ts_xml as suggested by Michael.

2022-02-10 21:48 UTC, r-owen commented on python/lsst/ts/salobj/base_csc.py
> +        If ``initial_state`` is invalid,
Looks like an accident. I'll back it out.

2022-02-10 21:49 UTC, r-owen commented on python/lsst/ts/salobj/base_csc.py
> +    valid_simulation_modes : `list` [`int`] or `None`
This is in a doc string, where it is OK to use `list` instead of `typing.List`. Good catch about `None`!

2022-02-10 21:51 UTC, r-owen commented on python/lsst/ts/salobj/base_csc_test_case.py
> +                    print("Warning: suprocess had already quit.")
Fixed (in two places, since a global search turned up a second).

2022-02-10 21:52 UTC, r-owen commented on tests/data/configs/bad_incomplete_no_site_file/README.txt
> +_default.yaml is not complete and there is no site-specific file.
Good catch. Fixed in 3 places.

2022-02-10 22:11 UTC, r-owen commented
Regarding the ts_xml issue: the problem there was a commit I had forgotten to push. ts_salobj already uses start.configurationOverride so I don't think it needs any changes. We'll see what Jenkins things now that I have fixed ts_xml.

2022-02-11 01:50 UTC, r-owen commented
There were some issues with LSST_SITE not being reliably set (which I missed because I had it set in my own environment). I pushed a fix.

2022-02-11 17:15 UTC, wvreeven approved these changes
Looks good to me now. Thanks for the additional changes.

2022-02-11 18:37 UTC, merged